name: Deploy to Cloudflare

on:
  # Trigger the workflow every time you push to the `main` branch
  # Using a different branch name? Replace `main` with your branch’s name
  push:
    paths:
      - 'frontend/**'
      - .github/workflows/cf_deploy.yml
    branches: [ main ]
  # Allows you to run this workflow manually from the Actions tab on GitHub.
  workflow_dispatch:
  
# Allow this job to clone the repo and create a page deployment
permissions:
  contents: read
  pages: write
  id-token: write
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout your repository using git
        uses: actions/checkout@v3
      - name: Install, build
        uses: withastro/action@v0
        with:
            path: ./frontend # The root location of your Astro project inside the repository. (optional)
            node-version: 16 # The specific version of Node that should be used to build your site. Defaults to 16. (optional)
            package-manager: pnpm # The Node package manager that should be used to install dependencies and build your site. Automatically detected based on your lockfile. (optional)
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: astro-dist
          path: ./frontend/dist
  deploy:
    runs-on: ubuntu-latest
    name: Deploy frontend
    needs: build
    steps:
      - uses: actions/checkout@v3
      - uses: actions/download-artifact@v3
        with:
          name: astro-dist
          path: ./frontend/dist
      - name: Publish
        uses: cloudflare/wrangler-action@2.0.0
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          command: pages publish ./frontend/dist --project-name=chengxiaoxingdotme